version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "arnold-app"
s3_bucket = "sam-arnold-slack-app"
s3_prefix = "arnold-app"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"

